// Preload all artwork images in the background after page loads.
// Images are fetched quietly so they're cached when you visit a project page.
window.addEventListener('load', function () {
    var images = [
        'artworks/grids/sublime.jpg',
        'artworks/grids/convo.jpg',
        'artworks/grids/value.jpg',
        'artworks/grids/frame.jpg',
        'artworks/grids/sanctity.jpg',
        'artworks/grids/orbit.jpg',
        'artworks/grids/cycle.jpg',
        'artworks/grids/portrait.jpg',
        'artworks/grids/geography.jpg',
        'artworks/grids/purity.jpg',
        'artworks/grids/zodiac.jpg',
        'artworks/grids/paranoia.jpg',
        'artworks/grids/mass.jpg',
        'artworks/grids/landscape.jpg',
        'artworks/recreations/dimension demo 3.jpg',
        'artworks/recreations/dimension demo 1.jpg',
        'artworks/recreations/swan_maidens.jpg',
        'artworks/recreations/eight_bells.jpg',
        'artworks/recreations/gold_apollo_venus.jpg',
        'artworks/recreations/hippolytus.jpg',
        'artworks/recreations/lysippos.jpg',
        'artworks/recreations/davids.jpg',
        'artworks/recreations/utagawa.jpg',
        'artworks/recreations/laocoon.jpg',
        'artworks/recreations/gauguin.jpg',
        'artworks/recreations/michelangelo_1.jpg',
        'artworks/recreations/michelangelo_2.jpg',
        'artworks/recreations/dimension demo 2.jpg',
        'artworks/recreations/eternal_love.jpg',
        'artworks/recreations/silver_venus.jpg',
        'artworks/recreations/sorolla.jpg',
        'artworks/recreations/olympia.jpg',
        'artworks/recreations/lassnig_1.jpg',
        'artworks/recreations/lassnig_2.jpg',
        'artworks/recreations/boucher.jpg',
        'artworks/feeling/img_1.jpg',
        'artworks/feeling/img_2.jpg',
        'artworks/feeling/img_3.jpg',
        'artworks/feeling/img_4.jpg',
        'artworks/feeling/img_5.jpg',
        'artworks/feeling/img_6.jpg',
        'artworks/feeling/img_7.jpg',
        'artworks/feeling/img_8.jpg',
        'artworks/feeling/img_9.jpg',
        'artworks/feeling/img_10.jpg',
        'artworks/feeling/img_11.jpg',
        'artworks/feeling/img_12.jpg',
        'artworks/feeling/img_13.jpg',
        'artworks/feeling/img_14.jpg',
        'artworks/feeling/img_15.jpg',
        'artworks/feeling/img_16.jpg',
        'artworks/feeling/img_17.jpg',
        'artworks/feeling/img_18.jpg',
        'artworks/feeling/img_19.jpg',
        'artworks/feeling/img_20.jpg',
        'artworks/self/you_can_dance.jpg',
        'artworks/self/stamp collector.jpg',
        'artworks/self/angelhood_pink.jpg',
        'artworks/self/untitled.jpg',
        'artworks/self/violet.jpg',
        'artworks/self/green.jpg',
        'artworks/self/hands.jpg',
        'artworks/self/polyethylene.jpg',
        'artworks/self/sincerity.jpg',
        'artworks/self/orange.jpg',
        'artworks/self/homecoming.jpg',
        'artworks/self/eyes.jpg',
        'artworks/self/double.jpg',
        'artworks/appreciation/mihir_thumb.jpg',
        'artworks/appreciation/mihir.jpg',
        'artworks/appreciation/multy.jpg',
        'artworks/appreciation/sarah.jpg',
        'artworks/appreciation/cj_thumb.jpg',
        'artworks/appreciation/cj.jpg',
        'artworks/appreciation/bella.jpg',
        'artworks/appreciation/shailen.jpg',
        'artworks/misc/ttd.jpg',
        'artworks/misc/cathy.jpg',
        'artworks/misc/ella_and_louis.jpg',
        'artworks/misc/quail_hunt.jpg',
        'artworks/misc/victoria.jpg',
        'artworks/misc/hammer.jpg',
        'artworks/misc/ascendant attendant.jpg',
        'artworks/misc/in_bed.jpg',
        'artworks/misc/jordan.jpg',
        'artworks/misc/trevor.jpg',
        'artworks/misc/david_thumb.jpg',
        'artworks/misc/david.jpg',
        'artworks/misc/beach.jpg'
    ];

    // Stagger loading so we don't hammer the connection
    var delay = 100;
    images.forEach(function (src, i) {
        setTimeout(function () {
            var img = new Image();
            img.src = src;
        }, delay * i);
    });
});
